version: '3'
services: 
    rabbitmq:
        image: rabbitmq:3.8-alpine
        ports: 
            - "5672:5672"
            - "15672:15672"
    distributer:
        image: distributer
    worker:
        image: worker
        deploy:
            mode: replicated
            replicas: 3
