version: '3.7'
services: 
    rabbitmq:
        image: rabbitmq:3.8-alpine
        ports: 
            - "5672:5672"
            - "15672:15672"
    distributer:
        image: distributer
        depends_on: 
            - rabbitmq
    worker:
        image: worker
        depends_on: 
            - rabbitmq
        deploy:
            mode: replicated
            replicas: 3
